FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json* bun.lockb* ./

RUN npm install

COPY . .

EXPOSE 5173

# Chạy chế độ Development (quan trọng: phải thêm --host để truy cập được từ ngoài)
CMD ["npm", "run", "dev", "--", "--host"]